import {
  SiAmazonaws,
  SiAntdesign,
  SiCss3,
  SiDocker,
  SiElectron,
  SiGraphql,
  SiHeroku,
  SiHtml5,
  SiLinux,
  SiMui,
  SiNestjs,
  SiNextdotjs,
  SiNodedotjs,
  SiPostgresql,
  SiPrisma,
  SiPwa,
  SiReact,
  SiReacthookform,
  SiReactquery,
  SiReactrouter,
  SiRedux,
  SiTailwindcss,
  SiTypescript,
  SiVite,
  SiZod,
} from "react-icons/si";

export const skills = {
  Backend: [
    { name: "Rest APIS", icon: null },
    { name: "NodeJS", icon: <SiNodedotjs /> },
    { name: "Typescript", icon: <SiTypescript /> },
    { name: "NestJS", icon: <SiNestjs /> },
    { name: "Prisma", icon: <SiPrisma /> },
    { name: "PostgreSQL", icon: <SiPostgresql /> },
    { name: "GraphQL", icon: <SiGraphql /> },
    { name: "Linux", icon: <SiLinux /> },
    { name: "AWS", icon: <SiAmazonaws /> },
    { name: "Heroku", icon: <SiHeroku /> },
    { name: "Docker", icon: <SiDocker /> },
  ],
  Frontend: [
    { name: "React", icon: <SiReact /> },
    { name: "Vite", icon: <SiVite /> },
    { name: "CSS", icon: <SiCss3 /> },
    { name: "HTML", icon: <SiHtml5 /> },
    { name: "NextJS", icon: <SiNextdotjs /> },
    { name: "React-Query", icon: <SiReactquery /> },
    { name: "TailwindCSS", icon: <SiTailwindcss /> },
    { name: "Electron", icon: <SiElectron /> },
    { name: "Antd", icon: <SiAntdesign /> },
    { name: "MUI", icon: <SiMui /> },
    { name: "PWA", icon: <SiPwa /> },
    { name: "React-Hook-Form", icon: <SiReacthookform /> },
    { name: "Zod", icon: <SiZod /> },
    { name: "Redux Toolkit", icon: <SiRedux /> },
    { name: "React-Router", icon: <SiReactrouter /> },
  ],
};
